services:
  solopg-mongo:
    image: docker.io/library/mongo:latest
    
    container_name: solopg-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
